version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: graphQL-tasks
    ports:
      - 5432:5432
    volumes:
      - ./docker/graphQL-tasks/init.d:/docker-entrypoint-initdb.d
      - ./docker/graphQL-tasks/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: udemy_user
      POSTGRES_PASSWORD: udemy_pass
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      POSTGRES_DB: udemydb
    hostname: postgres
    restart: always
    user: root
